# Generated by Django 4.0.5 on 2022-06-14 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelsInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('travel_name', models.CharField(max_length=20)),
                ('cost', models.FloatField()),
                ('date_added', models.DateField()),
                ('user_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudyInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('study_name', models.CharField(max_length=20)),
                ('cost', models.FloatField()),
                ('date_added', models.DateField()),
                ('user_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavingsInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('savings_name', models.CharField(max_length=20)),
                ('cost', models.FloatField()),
                ('date_added', models.DateField()),
                ('user_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('expense_name', models.CharField(max_length=20)),
                ('cost', models.FloatField()),
                ('date_added', models.DateField()),
                ('user_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EntertainmentInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entertainment_name', models.CharField(max_length=20)),
                ('cost', models.FloatField()),
                ('date_added', models.DateField()),
                ('user_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
